// Fixed bank the interrogator ranks against an uploaded image.
// CLIP scores these phrases; it does not write a caption.
export const PHRASES = [
  "a person",
  "a face",
  "a portrait",
  "a crowd of people",
  "a child",
  "a baby",
  "hands",
  "feet",
  "a dancer",
  "an athlete",
  "a musician",
  "a couple",
  "a family",
  "a profile of a face",
  "a smiling person",
  "a person seen from behind",
  "a seated person",
  "a standing person",
  "a person walking",
  "a group of friends",
  "a person holding a camera",
  "a person reading",
  "someone cooking",
  "people sitting at a table",
  "a crowd at a concert",
  "a sports game",
  "a wedding",
  "a cat",
  "a dog",
  "a bird",
  "a horse",
  "a fish",
  "an insect",
  "a butterfly",
  "a wild animal",
  "a farm animal",
  "a pet",
  "a dog running",
  "a cat sleeping",
  "birds flying",
  "a tree",
  "a forest",
  "flowers",
  "a bouquet",
  "flowers in a vase",
  "a mountain",
  "the ocean",
  "a beach",
  "waves on a beach",
  "a river",
  "a lake",
  "a desert",
  "a field",
  "the sky",
  "clouds",
  "a sunset",
  "snow",
  "rain",
  "a rainy street",
  "grass",
  "leaves",
  "autumn leaves",
  "a tree in winter",
  "a garden",
  "rocks",
  "a waterfall",
  "a night sky",
  "stars",
  "the moon",
  "a city",
  "a cityscape",
  "a street",
  "a building",
  "a building at night",
  "a house",
  "a room",
  "a kitchen",
  "a classroom",
  "an art studio",
  "a museum",
  "a church",
  "a factory",
  "a bridge",
  "a road",
  "a park",
  "a bedroom",
  "an office",
  "a shop",
  "a restaurant",
  "a library",
  "a hallway",
  "ruins",
  "a skyscraper",
  "a suburb",
  "a village",
  "an interior",
  "a seascape",
  "a car",
  "a bicycle",
  "a train",
  "a boat",
  "an airplane",
  "a chair",
  "a table",
  "a messy desk",
  "food on a plate",
  "a plate of food",
  "a birthday cake",
  "fruit",
  "a book",
  "clothing",
  "a pair of shoes",
  "a phone",
  "a computer",
  "a camera",
  "a cup",
  "a bottle",
  "a houseplant",
  "a toy",
  "a musical instrument",
  "a window",
  "a door",
  "a lamp",
  "a clock",
  "a mirror",
  "a bag",
  "glasses",
  "a hat",
  "jewelry",
  "tools",
  "dishes",
  "a bed",
  "a sofa",
  "a still life",
  "a landscape",
  "a self-portrait",
  "a nude figure",
  "a figure drawing",
  "an abstract composition",
  "a repeating pattern",
  "a logo",
  "lettering",
  "a poster",
  "a comic panel",
  "a map",
  "a diagram",
  "a sculpture",
  "a ceramic vessel",
  "fabric",
  "a textile",
  "graffiti on a wall",
  "a mural",
  "a sketchbook page",
  "a study of hands",
  "a study of drapery",
  "paint on a canvas",
  "a grid of images",
  "a blank wall",
  "a photograph",
  "a black and white photograph",
  "a color snapshot",
  "a film still",
  "a polaroid",
  "a contact sheet",
  "an oil painting",
  "a watercolor",
  "an acrylic painting",
  "a pencil drawing",
  "a charcoal drawing",
  "an ink drawing",
  "a pastel drawing",
  "a print",
  "a linocut",
  "an etching",
  "a collage",
  "a digital illustration",
  "a 3d render",
  "a screenshot",
  "pixel art",
  "a painting",
  "a drawing",
  "a sketch",
  "an animation frame",
  "a scanned drawing",
  "realistic",
  "abstract",
  "minimal",
  "documentary photography",
  "cinematic",
  "fashion photography",
  "street photography",
  "portrait photography",
  "landscape photography",
  "product photography",
  "scientific illustration",
  "a children's book illustration",
  "comic book art",
  "anime",
  "impressionist",
  "expressionist",
  "cubist",
  "surreal",
  "pop art",
  "baroque",
  "a renaissance painting",
  "art nouveau",
  "modernist",
  "contemporary art",
  "folk art",
  "geometric abstraction",
  "painterly",
  "high contrast",
  "soft focus",
  "blurry",
  "grainy film",
  "saturated color",
  "muted color",
  "monochrome",
  "warm light",
  "cool light",
  "harsh sunlight",
  "soft natural light",
  "studio lighting",
  "nighttime",
  "daytime",
  "a sunny day",
  "fog",
  "indoors",
  "outdoors",
  "a close-up",
  "a wide view",
  "an aerial view",
  "looking up",
  "looking down",
  "a centered composition",
  "a cropped frame",
  "motion blur",
  "a reflection",
  "a shadow",
  "a silhouette",
  "bright colors",
  "dark tones",
  "pastel colors",
  "earth tones",
  "neon colors",
  "mostly red",
  "mostly blue",
  "mostly green",
  "mostly yellow",
  "mostly pink",
  "black and white",
  "fire",
  "smoke",
  "water",
  "sand",
  "concrete",
  "wood",
  "metal",
  "glass",
  "paper",
  "skin",
  "hair",
  "eyes",
  "a smile",
  "a hand holding an object",
  "text on a page",
  "a sign",
  "a screen",
  "a stage",
  "a playground",
  "a market",
  "a cafe",
  "a subway",
  "a highway",
  "a farm",
  "a zoo animal",
  "a bird on a branch",
  "a boat on water",
  "cars in traffic",
  "a person on a bicycle",
  "two people talking",
  "a person lying down",
  "a close-up of a face",
  "a full body portrait",
  "an empty room",
  "a cluttered room",
  "a window with light coming through",
  "a shadow on a wall",
  "a reflection in a mirror",
  "food being prepared",
  "a table set for a meal",
  "a stack of books",
  "a single object on a plain background",
  "a pattern of shapes",
  "loose brushstrokes",
  "visible pencil lines",
  "a photograph of a painting",
  "a photo of a sculpture",
  "an artwork hanging on a wall",
  "a studio setup with lights",
  "a computer screen showing an image",
] as const;
